### ISSUE TITLE
cannot use the ref provided by useMouseLeave

### ISSUE THREAD

**Issue by raphaelbadia** [mjsarfatti/use-mouse-leave#1]
Hello,

I have a use case where I need to get the element's node like this:

```jsx

 const [mouseLeft, ref] = useMouseLeave();
<div
      ref={ref}
      className={classes.rootEvent}
      onMouseEnter={() => {
        
        someFunction(ref.current, item);
      }}
    >

```

but when I log ref I get this : 
![CleanShot 2020-03-11 at 18 23 22](https://user-images.githubusercontent.com/1901628/76445247-69071380-63c5-11ea-99b4-2ddb8b3bde81.png)

An easy workaround is to wrap my first ref with a second ref, but I think it could be improved ?

Sorry for my bad english and thanks for this package, it solves nicely my problem :)

**Comment by mjsarfatti** [comment]
Hey @raphaelbadia,

I'm afraid I'm not sure what the problem is. `ref.current` should refer to the `<div>` element in your example. Does it not?

Are you able to share a simple codesandbox.io example? You can fork the demo: https://codesandbox.io/s/determined-goldwasser-35ukt

**Comment by raphaelbadia** [comment]
Hi there, thanks for the sandbox. 
I added the following code to the example: 
```jsx
onMouseEnter={() => {
            console.log(
              "I expected ref.current to be an html element but it is ",
              ref.current
            );
          }}
```
But it returns `undefined`, please see the console output here : https://codesandbox.io/s/eloquent-cori-dfvj6 

And this is my current workaround to get something similar : https://codesandbox.io/s/blazing-field-jhzk9

**Comment by raphaelbadia** [comment]
I read the source and this article https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780 , I didn't know this pattern ! It seems that to expose the div inside the ref you would have to change the API and that would be weird... The workaround is fine I think

**Comment by mjsarfatti** [comment]
Oh I see now, good catch! I didn't know about this problem.

Would you like to contribute a PR to solve this issue?

**Comment by raphaelbadia** [comment]
Done in #3 , what do you think about it ?
